### PR TITLE
Support for including and excluding conversations in export

### PR DESCRIPTION
**Pull request by rusq**
* Add support for including and excluding conversations in export
* Get rid of github.com/pkg/errors dependency
* refactor Dump functions, deprecating a bunch.
* Remove `-i` parameter, replacing it with '@' prefix, i.e. `@my_list.txt`
* Rename structures.SlackURL to SlackLink and adopt it's usage in slackdump.  It's now possible to specify the thread without the need for URL: `CHANNEL:12345678.0000` will link to a thread with TS `12345678.0000` in the `CHANNEL`.
* Introduce the '^' prefix to exclude the conversations on the command line, i.e. `^C123456` to exclude channel `C123456` from export.

### CODE REVIEW

**Comment by hiro-flab** [comment]
@rusq 

I executed the following two commands to see the ability to exclude specific channels:

```
slackdump -export export1.zip C123456
slackdump -export export2.zip ^C123456
```

Both produced a ZIP file with the data for the channel C123456.

The slackdump version is `slackdump-v2.2.6-windows-amd64`.
Please let me know if I'm using the wrong arguments for [command line export](https://github.com/rusq/slackdump/blob/master/doc/usage-export.rst).

**Comment by yoshimotomasahir** [comment]
@rusq

I executed the following two commands to see the ability to exclude specific channels:

slackdump -export export1.zip C123456
slackdump -export export2.zip ^C123456
Both produced a ZIP file with the data for the channel C123456.

The slackdump version is slackdump-v2.2.6-windows-amd64.
Please let me know if I'm using the wrong arguments for [command line export](https://github.com/rusq/slackdump/blob/master/doc/usage-export.rst).

**Comment by yoshimotomasahir** [comment]
@rusq 

Thank you for testing.

I forgot that the caret `^` is treated specially in the Windows command prompt.
Surrounding the `^C0123456` with double quotation `""` like `"^C0123456"` solved.

**Comment by rusq** [comment]
I'll need to document that, that's for sure. Thank you :)

**Pull request merged**
